swagger_server/itm/itm_scenario_session.py
swagger_server/itm/itm_session_scenario_object.py

* Hide Burn injuries at start;
* Reveal injuries in state based on ADM actions based on resolution of ITM-82;
* Do not treat/remove injuries that haven’t been discovered by ADMs;
* Validate that you have sufficient Supplies to treat an injury; and
* Only remove an Injury and decrement Supplies if the APPLY_TREATMENT action specifies the correct treatment/location for the injury.

ITM-83: Address injury/treatment TODOs

---

swagger_server/itm/itm_scenario_session.py

* Abort and restart session for same ADM name (helps crashing clients)
Fixes #6 
One way to test this is to introduce a divide by zero error after a few actions, then try to re-run/re-connect to the server.

ITM-91: Allow crashing clients to start new sessions

---

swagger_server/itm/itm_scenario_session.py
swagger_server/models/action.py
swagger_server/swagger/swagger.yaml

* Add END_SCENARIO to action space/API;
* SoarTech:  END_SCENARIO is always available; server only ends the scenario in response to END_SCENARIO ;
* BBN:  END_SCENARIO is not initially available; once ADM performs a MOVE_TO_EVAC action, the only available actions will be END_SCENARIO and TAG_PATIENT, the latter of which is always available.
Testing requires pulling ITM-96 branch from `itm-evaluation-client`.

ITM-96:  Add END_SCENARIO to the API and tweak custom September scenario/action progression

---

swagger_server/itm/itm_scenario_configs/adept/scenario_1/alignment_target.yaml
swagger_server/itm/itm_scenario_configs/adept/scenario_1/probe_1.yaml
swagger_server/itm/itm_scenario_configs/adept/scenario_1/probe_2.yaml
swagger_server/itm/itm_scenario_configs/soartech/scenario_1/alignment_target.yaml
swagger_server/itm/itm_scenario_configs/soartech/scenario_1/probe_1.yaml
swagger_server/itm/itm_scenario_session.py

* ITM-87: Integrate with TA1 (Soartech)
* ITM-88: Integrate with TA1 (ADEPT)
Note:  for this to work, you have to change the first line of SoarTech's `itm_app/data/scenarios/st-september-2023-mvp2/anchors.yaml` from `st-september-2023-mvp` to `st-september-2023-mvp2`.
Also, due to default port conflicts, you have to set `TA3_PORT` to 8081 and `ADEPT_PORT` to 8080.
Alternatively, you can change the port in ADEPT's `openapi_server/__main__.py` from 8080 to 8081 and keep TA3 at 8080.
Don't forget to set `self.ta1_integration` to `True` when testing the TA1s individually (i.e., not testing the `eval` session).
Note that if the client calls the `END_SCENARIO` action prior to answering the probe, then SoarTech will return a 404 in the `/api/v1/alignment/session` call.
Finally, note that …

Configured evaluation probes for SoarTech and BBN/ADEPT

---

.gitattributes
swagger/swagger.yaml
swagger_server/itm/itm_scenario_configs/adept/scenario_1/probe_1.yaml
swagger_server/itm/itm_scenario_configs/adept/scenario_1/probe_2.yaml
swagger_server/itm/itm_scenario_configs/soartech/scenario_1/probe_1.yaml
swagger_server/itm/itm_scenario_configs/soartech/scenario_1/scenario.yaml
swagger_server/itm/itm_scenario_session.py
swagger_server/models/action.py
swagger_server/models/casualty.py
swagger_server/models/state.py

Fixes a few things that were discovered after the final September release of the TA3 server and ADM client:
* Remove `patients_treated` from the server (and its use in `take_action`-- it’s a SoarTech scenario hack that ended up not being needed.
* Audit every description in the yaml files and ensure no reference to mvp, probes, and other MVP-1 phenomena.
* Improve error messages with invalid values, especially when validating action.
* Remove `EXPECTANT` from the relationship enum.
* Change lacerations of locations other than the thigh from `Hemostatic gauze` to `Pressure bandage`.
* Validate that the location and treatment parameter in `APPLY_TREATMENT` matches something in the YAML/API.
* Add ADM name to the `start_scenario` output, for ease of interpretation/parsing of output.
* …

ITM-106: Post-September demo cleanup tasks

---

swagger/swagger.yaml
swagger_server/itm/itm_action_handler.py
swagger_server/itm/itm_scenario_session.py

These were some thing that were not encountered/needed in the September milestone, but are now fixed:
* Fix error validating bad tag categories specified by the ADM
* Fix elapsed time saving to database
* Fix bug in handling SITREP of all casualties (i.e., when no `casualty_id` is specified)
* Handle when ADM calls `start_scenario` prior to ending the previous scenario via `END_SCENARIO`.
* Return 400 code
* Update/fix some casualty injuries/treatments
**NOTE**:  There will be as small PR forthcoming for `itm-evaluation-client` for the minor changes to the swagger API.

ITM-121 and ITM-119: more minor server fixes

---

swagger/swagger.yaml
swagger_server/controllers/itm_ta2_eval_controller.py
swagger_server/itm/itm_eval_scenarios/adept/scenario_1/scenario.yaml
swagger_server/itm/itm_eval_scenarios/adept/scenario_2/scenario.yaml
swagger_server/itm/itm_eval_scenarios/adept/scenario_3/scenario.yaml
swagger_server/itm/itm_eval_scenarios/adept/scenario_4/scenario.yaml
swagger_server/itm/itm_eval_scenarios/soartech/scenario_1/scenario.yaml
swagger_server/itm/itm_eval_scenarios/soartech/scenario_2/scenario.yaml
swagger_server/itm/itm_eval_scenarios/soartech/scenario_3/scenario.yaml
swagger_server/itm/itm_eval_scenarios/soartech/scenario_4/scenario.yaml
swagger_server/itm/itm_scenario.py
swagger_server/itm/itm_session.py
swagger_server/itm/itm_training_scenarios/adept/scenario_1/scenario.yaml
swagger_server/itm/itm_training_scenarios/adept/scenario_2/scenario.yaml
swagger_server/itm/itm_training_scenarios/adept/scenario_3/scenario.yaml
swagger_server/itm/itm_training_scenarios/soartech/scenario_1/scenario.yaml
swagger_server/itm/itm_training_scenarios/soartech/scenario_2/scenario.yaml
swagger_server/itm/itm_training_scenarios/soartech/scenario_3/scenario.yaml
swagger_server/itm/itm_training_scenarios/soartech/scenario_4/scenario.yaml
swagger_server/models/vitals.py

* ITM-186: Better error-handling when TA1 is unreachable
* Change server default to run integrated with TA1
* ITM-225: Remove the restrictions on specifying a `scenario_id` in `start_scenario()`
Run against [client branch ITM-225](https://github.com/NextCenturyCorporation/itm-evaluation-client/tree/ITM-225).

ITM-186 and ITM-225

---

swagger_server/itm/itm_action_handler.py
swagger_server/itm/itm_eval_scenarios/adept/scenario_1/scenario.yaml
swagger_server/itm/itm_eval_scenarios/soartech/scenario_1/alignment_target.yaml
swagger_server/itm/itm_eval_scenarios/soartech/scenario_2/alignment_target.yaml
swagger_server/itm/itm_eval_scenarios/soartech/scenario_3/alignment_target.yaml
swagger_server/itm/itm_eval_scenarios/soartech/scenario_4/alignment_target.yaml
swagger_server/itm/itm_scenario.py
swagger_server/itm/itm_scenario_reader.py
swagger_server/itm/itm_scene.py
swagger_server/itm/treatment_times_config/actionTimes.json

This PR includes:
1. Support pre-configured treated injuries and initially visible vitals;
2. Fix scene transitioning bug;
3. Add missing action times (elapsed time associated with ADM actions); and
4. Made minor tweak to DIRECT_MOBILE_CHARACTERS (limit to to CALM or UPSET characters)
To test, use a custom scenario crafted to test the changes, attached [here](https://github.com/NextCenturyCorporation/itm-evaluation-server/files/14502186/scenario.zip).  Place it in `itm/itm_eval_scenarios/adept/scenario_1/scenario.yaml`, replacing the `scenario.yaml` that's currently there.
Also, use the [client's ITM-241 branch](https://github.com/NextCenturyCorporation/itm-evaluation-client/tree/ITM-241) and run: 
`python itm_minimal_runner.py --adm_name foobar --session adept --scenario test-1`.
See the …

ITM-241: Support pre-configured treated injuries and initially visible vitals

---

swagger_server/itm/itm_history.py
swagger_server/itm/itm_session.py

Change history filename to `<scenario_id>-<ta1>-<alignment>-<date>.json` e.g.
- e.g., `MetricsEval.MD4-Jungle-adept-high-Mar13-11.45.36.json`
- e.g., `submarine-1-soartech-high-Mar13-11.44.45.json`
To test, run the development client with the  `--eval` flag and check out the results in the server's `itm_history_output` folder.
This requires both TA1 servers running, but you can also try a standalone session (e.g., with `--session adept` instead of `--eval`) but change `self.save_history = True` in `itm_session.py`.

ITM-252: Better output file naming for JSON

---

requirements.txt
swagger_server/itm/itm_history.py
swagger_server/itm/itm_session.py

1. Get a temporary aws access token: 
a. you'll need aws-cli installed
b. grab [saml-caci-all.zip](https://caci.servicenowservices.com/sys_attachment.do?sys_id=1c127be01b34f5d01afb0e9ee54bcbfa) from [here](https://caci.servicenowservices.com/caci?id=kb_article_view&table=kb_knowledge&sys_kb_id=4c12b3e01b34f5d01afb0e9ee54bcb9b&recordUrl=%2Fkb_view.do%3Fsys_kb_id%3D4c12b3e01b34f5d01afb0e9ee54bcb9b) (2nd section - # 3)
c. unzip the above and run your OS specific command
d. it'll generate a config and credentials file
e. in your .aws folder (you'll have one in your home dir after installing the aws-cli), back up your config/crendetials file and replace it with the ones the saml tool created
f. in the credentials file rename `[saml]` to `[default]`
g. you should now be able to issue aws …

ITM-253 - Eval server history to s3

---

requirements.txt

Created a ticket but not sure why I'm not seeing it on the board:
https://nextcentury.atlassian.net/browse/ITM-294
There was a conflict with the python-dateutil when running inside the container.  I pinned a newer version 2.9.0.  Everything seems to be working.  I updated in production to test.
To test from the itm-evaluation-client:
export TA3_PORT="443"
export TA3_HOSTNAME="https://darpaitm.caci.com"
python itm_minimal_runner.py --adm_name test --session eval

ITM-294 - Fix TA3 Eval API Error

---

swagger_server/itm/data/metrics/scenarios/metrics-adept-eval-freeform-desert.yaml
swagger_server/itm/data/metrics/scenarios/metrics-adept-eval-freeform-jungle.yaml
swagger_server/itm/data/metrics/scenarios/metrics-adept-eval-freeform-submarine.yaml
swagger_server/itm/data/metrics/scenarios/metrics-adept-eval-freeform-urban.yaml
swagger_server/itm/data/metrics/scenarios/metrics-soartech-eval-freeform-desert.yaml
swagger_server/itm/data/metrics/scenarios/metrics-soartech-eval-freeform-jungle.yaml
swagger_server/itm/data/metrics/scenarios/metrics-soartech-eval-freeform-submarine.yaml
swagger_server/itm/data/metrics/scenarios/metrics-soartech-eval-freeform-urban.yaml

There are eight scenarios-- four soartech and four adept-- but the scenarios are identical.
These will be run as part of an `eval` session, but no communication with TA1 will happen for these scenarios (as there are no probes or probe responses).  Session alignment will be logged in history always as 0.5, and can be ignored.
To test, run an evaluation session with the TA3 client (or a TA2 ADM) and ensure that eight JSON files are created with names like, e.g., `freeform-desert-adept-high-Apr04-11.34.46.json`.

Added freeform (open world) scenarios

---

swagger/swagger.yaml
swagger_server/controllers/itm_ta2_eval_controller.py
swagger_server/itm/itm_session.py

Currently, just logs the profile to history.  A new ticket would expand the notion of ADM profile for multiple KDMAs, which will probably entail some discussion down the line.
Test using the corresponding [ITM-300](https://github.com/NextCenturyCorporation/itm-evaluation-client/tree/ITM-300) client branch.
[ITM-300]: https://nextcentury.atlassian.net/browse/ITM-300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ITM-300: add adm_profile optional session parameter

---

swagger_server/itm/itm_action_handler.py

To test, what I did was add
```
if random.randint(1, 3) == 3:
random_action = Action(action_id='foobar', action_type='END_SCENE')
```
just before `if (paths["enabled"]):` in `itm_minimal_runner.py` on `development`.  Then I ran the minimal runner:
- `python itm_minimal_runner.py --session adept --name foobar --scenario MetricsEval.MD5-Desert`
Then I repeated it, changing `END_SCENE` to `CHECK_RESPIRATION`.
**NOTE**: ADMs can still take an action where they use the `action_id` from `get_available_actions`, then send whatever the heck they want for the `action_type`, `parameters`, etc.  As long as the action is well-formed and isn't restricted, the server will allow it.  In other words, it doesn't check that the incoming action matches the configured action with the specified `action_id`. …

Return 400 error code for restricted actions.

---

swagger/swagger.yaml
swagger_server/itm/data/metrics/scenarios/metrics-adept-eval-freeform-desert.yaml
swagger_server/itm/data/metrics/scenarios/metrics-adept-eval-freeform-jungle.yaml
swagger_server/itm/data/metrics/scenarios/metrics-adept-eval-freeform-submarine.yaml
swagger_server/itm/data/metrics/scenarios/metrics-adept-eval-freeform-urban.yaml
swagger_server/itm/data/metrics/scenarios/metrics-soartech-eval-freeform-desert.yaml
swagger_server/itm/data/metrics/scenarios/metrics-soartech-eval-freeform-jungle.yaml
swagger_server/itm/data/metrics/scenarios/metrics-soartech-eval-freeform-submarine.yaml
swagger_server/itm/data/metrics/scenarios/metrics-soartech-eval-freeform-urban.yaml
swagger_server/itm/itm_action_handler.py
swagger_server/itm/itm_scenario_reader.py
swagger_server/models/character.py

Added `Character.hasBlanket` so that ADMs can tell if a blanket has been applied.  Normally treatments are conveyed via the `Injury.status` set to `treated`, but Blankets don't treat an injury (but do need to be reflected in the character).
Also added the new supplies to freeform scenarios.
Also, ninja edit to add treatment to Forehead Scape / Abrasion now that it's implemented in the sim, see ITM-406.
To test, use the Human input simulator in the [ITM-401](https://github.com/NextCenturyCorporation/itm-evaluation-client/tree/ITM-401) branch of the `itm-evaluation-client`:
- `python itm_human_input.py --session adept --scenario freeform-desert`
You don't need to run a TA1 server.
The Human input simulator is a little wonky if you've never used it before.  But basically:
1.  Type `s` then …

ITM:401: Indicate to ADMs that a blanket has been applied

---

swagger/swagger.yaml
swagger_server/itm/data/metrics/scenarios/metrics-adept-eval-desert.yaml
swagger_server/itm/data/metrics/scenarios/metrics-adept-eval-freeform-desert.yaml
swagger_server/itm/data/metrics/scenarios/metrics-adept-eval-freeform-jungle.yaml
swagger_server/itm/data/metrics/scenarios/metrics-adept-eval-freeform-submarine.yaml
swagger_server/itm/data/metrics/scenarios/metrics-adept-eval-freeform-urban.yaml
swagger_server/itm/data/metrics/scenarios/metrics-adept-eval-jungle.yaml
swagger_server/itm/data/metrics/scenarios/metrics-adept-eval-submarine.yaml
swagger_server/itm/data/metrics/scenarios/metrics-adept-eval-urban.yaml
swagger_server/itm/data/metrics/scenarios/metrics-adept-training-desert.yaml
swagger_server/itm/data/metrics/scenarios/metrics-adept-training-jungle.yaml
swagger_server/itm/data/metrics/scenarios/metrics-adept-training-submarine.yaml
swagger_server/itm/data/metrics/scenarios/metrics-adept-training-urban.yaml
swagger_server/itm/data/metrics/scenarios/metrics-soartech-eval-desert.yaml
swagger_server/itm/data/metrics/scenarios/metrics-soartech-eval-freeform-desert.yaml
swagger_server/itm/data/metrics/scenarios/metrics-soartech-eval-freeform-jungle.yaml
swagger_server/itm/data/metrics/scenarios/metrics-soartech-eval-freeform-submarine.yaml
swagger_server/itm/data/metrics/scenarios/metrics-soartech-eval-freeform-urban.yaml
swagger_server/itm/data/metrics/scenarios/metrics-soartech-eval-jungle.yaml
swagger_server/itm/data/metrics/scenarios/metrics-soartech-eval-submarine.yaml
swagger_server/itm/data/metrics/scenarios/metrics-soartech-eval-urban.yaml
swagger_server/itm/data/metrics/scenarios/metrics-soartech-training-desert.yaml
swagger_server/itm/data/metrics/scenarios/metrics-soartech-training-jungle.yaml
swagger_server/itm/data/metrics/scenarios/metrics-soartech-training-submarine.yaml
swagger_server/itm/data/metrics/scenarios/metrics-soartech-training-urban.yaml
swagger_server/itm/itm_action_handler.py
swagger_server/itm/itm_scenario_reader.py
swagger_server/itm/itm_scene.py
swagger_server/models/vitals.py

* Remove `conscious` vital and update scenarios accordingly;
* Fix bug ending scene action mappings.
Use with the client [ITM-409](https://github.com/NextCenturyCorporation/itm-evaluation-client/tree/ITM-409) branch and corresponding [PR](https://github.com/NextCenturyCorporation/itm-evaluation-client/pull/32).
One way to test is with something like
- `python itm_minimal_runner.py --session adept --name foobar --count 200`
This will run 200 copies of ADEPT evaluation scenarios (and freeform scenarios) without the TA1 server.
Then switch `adept` to `soartech` and then repeat both with `--training`.
And try anything else you wish, such as an `eval` session.
[ITM-409]: https://nextcentury.atlassian.net/browse/ITM-409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …

ITM-409: Remove "conscious" from Vitals

---

swagger/swagger.yaml
swagger_server/itm/data/actionTimes.json
swagger_server/itm/data/metrics/scenarios/metrics-adept-eval-freeform-desert.yaml
swagger_server/itm/data/metrics/scenarios/metrics-adept-eval-freeform-jungle.yaml
swagger_server/itm/data/metrics/scenarios/metrics-adept-eval-freeform-submarine.yaml
swagger_server/itm/data/metrics/scenarios/metrics-adept-eval-freeform-urban.yaml
swagger_server/itm/data/metrics/scenarios/metrics-soartech-eval-freeform-desert.yaml
swagger_server/itm/data/metrics/scenarios/metrics-soartech-eval-freeform-jungle.yaml
swagger_server/itm/data/metrics/scenarios/metrics-soartech-eval-freeform-submarine.yaml
swagger_server/itm/data/metrics/scenarios/metrics-soartech-eval-freeform-urban.yaml
swagger_server/itm/itm_action_handler.py
swagger_server/models/supply_type_enum.py

Use the [ITM-420 client branch](https://github.com/NextCenturyCorporation/itm-evaluation-client/tree/ITM-420) and run soartech and adept session types.  You can also use the human ADM simulator to make sure you can choose the fentanyl lollipop treatment (location is ignored).
[Here's](https://github.com/NextCenturyCorporation/itm-evaluation-client/pull/34) the corresponding client PR.

ITM-420:  Added fentanyl lollipop

---

swagger/swagger.yaml
swagger_server/controllers/itm_ta2_eval_controller.py
swagger_server/itm/data/metrics/local_alignment_targets/test/test_alignment_target.yaml
swagger_server/itm/data/metrics/test/removed_characters.yaml
swagger_server/itm/data/metrics/test/reusable_supplies.yaml
swagger_server/itm/data/metrics/test/sample.yaml
swagger_server/itm/data/metrics/test/unordered_scenes.yaml
swagger_server/itm/itm_action_handler.py
swagger_server/itm/itm_scenario.py
swagger_server/itm/itm_scene.py
swagger_server/itm/itm_session.py

- Added a testing framework / session type for testing PRs and a precursor to regression testing (incompatible with training mode);
- Updated sample YAML file from early in Metrics eval to current development;
- Wrote some YAML examples that use the various features of the scenario YAML file that we can run routinely after every ticket / new feature;
- Made `CHECK_BLOOD_OXYGEN` and `CHECK_ALL_VITALS` fail if there is no Pulse Oximeter in the supplies;
- Also don't add them as actions if no pulse ox is available.
- Fixed regression introduced in ITM-386.
See corresponding [client PR](https://github.com/NextCenturyCorporation/itm-evaluation-client/pull/36) and [branch](https://github.com/NextCenturyCorporation/itm-evaluation-client/tree/ITM-385).
To test, run test sessions (maybe with a …

ITM-385: Add test session and YAML examples

---

.gitignore
swagger/swagger.yaml
swagger_server/itm/data/metrics/test/sample.yaml
swagger_server/itm/itm_scenario_reader.py
swagger_server/itm/itm_scene.py
swagger_server/models/action.py
swagger_server/models/action_mapping.py

ADEPT would like to be able to convey to an ADM that there is an expected change in threat level if a particular action is performed.
Work performed:
- Added `threat_state` to the action mappings (which means they’ll also have to be in the `Action` class so that ADMs see it.  The `threat_state` will be ignored by the server for incoming actions.
- Updated sample YAML to show usage of this feature.
Use with client branch [ITM-439](https://github.com/NextCenturyCorporation/itm-evaluation-client/tree/ITM-439) and its corresponding [PR](https://github.com/NextCenturyCorporation/itm-evaluation-client/pull/40).
To test, use `itm_human_input.py`:
* `python itm_human_input.py --session test --scenario sample-1`
* Type `s` and `c` to start the scenario.
* Ensure there is one `aid_delay` object in …

ITM-439: Added threat_state to ActionMappings and Action

---

swagger/swagger.yaml
swagger_server/itm/data/metrics/test/sample.yaml
swagger_server/models/aid.py
swagger_server/models/event.py

- Add 'when' parameter to events;
- Rename trauma level (1-5) to medical role (1-4) based on different resource
- e.g., `Aid.level` -> `Aid.role`

ITM-485: Miscellaneous late requested changes

---

swagger/swagger.yaml
swagger_server/itm/data/metrics/test/removed_characters.yaml
swagger_server/itm/data/metrics/test/sample.yaml
swagger_server/itm/data/metrics/test/unordered_scenes.yaml
swagger_server/itm/data/metrics/test/unseen_characters.yaml
swagger_server/itm/itm_action_handler.py
swagger_server/itm/itm_scenario.py
swagger_server/models/aid.py
swagger_server/models/event.py

- Only successful treatments consume supplies;
- Automatically persist characters if scenario loops back to first scene.
- A few minor fixes to test scenarios
NOTE:  Originally this ticket intended to sync server behavior with the sim.  However, it’s hard to tell which behavior in the sim is desired, and which behavior are bugs, so we went with the simple heuristic of "only successful treatments consume supplies and overtreating never does."
To test, use a client (probably the human ADM sim) and select bad treatment options (use pressure bandage on an amputation or a Decompression Needle on a broken forearm) and ensure that no supplies are decremented, the injury remains untreated, but discoverable injuries and vitals are revealed.  Then make sure that a correct treatment treats the …

ITM-432: Only successful treatments consume supplies

---

swagger_server/itm/itm_action_handler.py
swagger_server/itm/itm_scenario_reader.py

If there is no pulse oximeter in the state, then `CHECK_ALL_VITALS` is allowed/valid, but blood oxygen won’t be returned.
See trivial, documentation-only [client PR](https://github.com/NextCenturyCorporation/itm-evaluation-client/pull/51)
To test:
- Run a `test` session via the `itm_minimal_runner` in the client repo; it should complete normally.
- Switch to `development` branch.
- Change "dryrun" to "metrics" in `itm_session` line 29.
- Run a "soartech" session via the `itm_minimal_runner` in the client repo; note error.
- Switch back to `ITM-509` branch.
- Change "dryrun" to "metrics" in `itm_session` line 29.
- Run a "soartech" session via the `itm_minimal_runner` in the client repo; this time it should work.

ITM-509: Allow CHECK_ALL_VITALS when no pulse ox, but don't check blood ox

---

swagger_server/itm/itm_scenario.py
swagger_server/itm/itm_session.py

Easiest way to test is with `itm_human_input.py` (make sure the scene id is there, but no probe response), or print out the state after an action in the minimal runner.  Use a test session with `--scenario sample-1`.

ITM-520: Return scene ID in state in all session types

---

.gitignore
README.md
swagger/swagger.yaml
swagger_server/itm/data/dryrun/local_alignment_targets/adept/ingroup_bias_1.yaml
swagger_server/itm/data/dryrun/local_alignment_targets/adept/ingroup_bias_5.yaml
swagger_server/itm/data/dryrun/local_alignment_targets/adept/ingroup_bias_9.yaml
swagger_server/itm/data/dryrun/local_alignment_targets/adept/moral_judgement_1.yaml
swagger_server/itm/data/dryrun/local_alignment_targets/adept/moral_judgement_5.yaml
swagger_server/itm/data/dryrun/local_alignment_targets/adept/moral_judgement_9.yaml
swagger_server/itm/data/dryrun/local_alignment_targets/soartech/qol_1.yaml
swagger_server/itm/data/dryrun/local_alignment_targets/soartech/qol_5.yaml
swagger_server/itm/data/dryrun/local_alignment_targets/soartech/qol_9.yaml
swagger_server/itm/data/dryrun/local_alignment_targets/soartech/vol_1.yaml
swagger_server/itm/data/dryrun/local_alignment_targets/soartech/vol_5.yaml
swagger_server/itm/data/dryrun/local_alignment_targets/soartech/vol_9.yaml
swagger_server/itm/itm_action_handler.py
swagger_server/itm/itm_scenario.py
swagger_server/itm/itm_scene.py
swagger_server/itm/itm_session.py
swagger_server/itm/itm_ta1_controller.py
swagger_server/models/alignment_results.py

- Removed `kdma_values` from `AlignmentResults`, in accordance with program changes. (ITM-478)
- Renamed various IDs to what TA1 is actually using (e.g., alignment targets, kdmas)
- Better handling/logging of TA1 server errors.
- Changed ADM output filenames since we're no longer using high/low
- Bugfixes.
To test, the best case scenario is to run the latest ADEPT and SoarTech servers and run the various session types against them.
If you haven't already, you'll have to copy the TA1 scenarios to your configured location.  I'll need to send them to you under separate cover because they have KDMAs unredacted so cannot be posted publicly.
I would change ITMSession's `self.ta1_integration` to True, then run the various TA1 session types:
- `python itm_minimal_runner.py --name foobar --session …

ITM-478/521/522:  Integrate with TA1 Dry Run servers

---

swagger_server/itm/itm_session.py

This happens before action validation, and is to ensure ADM didn't change a pre-configured action in ways it shouldn't.  Right now, the server is very trusting...
To test, what I did was to modify the `itm_minimal_runner.py` client to hack up the action it sends.  After `action = get_next_action()`, add something like:
```
if random.randint(0, 5) == 3:
action.action_type = "DIRECT_MOBILE_CHARACTERS"
```
Then run, say, an adept session like `python itm_minimal_runner.py --session adept --name foobar`.
Eventually, you should get an error about the `action_type` being wrong.
Try replacing the second line above with other hacks (one at a time) to get different error messages:
- `action.character_id = 'foobar'`
- `action.intent_action = True`
- `action.parameters = {"foobar": "asdf"}`
- …

ITM-526:  Add action pre-validation step 

---

.gitignore
swagger/swagger.yaml
swagger_server/itm/data/dryrun/local_alignment_targets/soartech/qol-human-1774519-SplitEvenBinary.yaml
swagger_server/itm/data/dryrun/local_alignment_targets/soartech/qol-synth-HighExtreme.yaml
swagger_server/itm/data/dryrun/local_alignment_targets/soartech/qol-synth-LowExtreme.yaml
swagger_server/itm/data/dryrun/local_alignment_targets/soartech/vol-human-7040555-SplitEvenBinary.yaml
swagger_server/itm/data/dryrun/local_alignment_targets/soartech/vol-synth-HighExtreme.yaml
swagger_server/itm/data/dryrun/local_alignment_targets/soartech/vol-synth-LowExtreme.yaml
swagger_server/itm/data/dryrun/test/conditional_mappings.yaml
swagger_server/itm/data/dryrun/test/sample.yaml
swagger_server/itm/itm_scenario_reader.py
swagger_server/itm/itm_scene.py
swagger_server/itm/itm_session.py
swagger_server/models/action_mapping.py

Changes:
- Break action mapping conditions into probe and action conditions;
- Update sample yaml and create new test;
- Fix two minor bugs in scenario reader (one of which was reported by TA2); and
- Add `CHECK_ALL_VITALS` to action list (if unrestricted) even if there's no pulse ox (this is okay because of ITM-509).
Also see [client PR](https://github.com/NextCenturyCorporation/itm-evaluation-client/pull/59), but the only changes were regenerating from the swagger file and updating the README.
To test, run Conditional action mappings test either multiple times via `itm_minimal_client` or interactively with the human client, and ensure that the actions taken result in the correct probe responses and available actions.  E.g.:
- `python itm_minimal_runner.py --name foobar --session test …

ITM-539:  Break action mapping conditions into probe and action conditions

---

swagger_server/itm/data/dryrun/test/multi-injuries.yaml
swagger_server/itm/itm_action_handler.py

Work performed:
- Handle multiple injuries at one place;
- Log intent action parameters;
- Fix bug with forearm punctures.
You can switch to DEBUG logging (in `itm_session.py`) to see the detailed injury treatment logging.
To test, use the minimal and/or the human ADM test client:
- `python itm_minimal_runner.py --name testinj --session test --scenario multi_injuries`
- `python itm_human_input.py --session test --scenario multi_injuries`
Things to look for:
- By the end of the scenarios, all patient injuries are at least partially treated.
- When you apply a pressure bandage to Mike, it treats both the abrasion and laceration.
- Supplies are always decremented after successful treatment; otherwise nothing is decremented.
- Quantized injuries are properly treated, changing status to …

ITM-568:  Allow multiple injuries in a single location

---

swagger_server/config.ini.template
swagger_server/config_util.py
swagger_server/itm/itm_session.py

Work performed:
- Added ADEPT to the current scenario runner configuration.
- Refactored or replaced indicated areas (TODO) in `start_session`;
- Added `ALWAYS_CONNECT_TO_TA1` (for non-training, non-eval sessions) to configuration; and
- Allowed config vars to have embedded environment variables (Parallax request).
To test:
- First, update your `config.ini` with the new stuff added to the template.
- Run all session types (while connected to TA1 servers):  `eval`, `soartech`, `adept`, and `test`.
- Refer to new logging to see which scenarios/alignment targets are configured to run.
- Update your `config.ini` to remove a subset of ST and ADEPT scenarios/alignment targets, and try again.
- Make sure that your config file is internally consistent (e.g., `ADEPT_EVAL_FILENAMES` is in …

ITM-586: Final DRE enhancements to scenario runner/config

---

swagger/swagger.yaml
swagger_server/controllers/itm_ta2_eval_controller.py
swagger_server/itm/itm_session.py
swagger_server/models/vitals.py

Added solo (standalone) training mode that returns kdmas but doesn't request session alignment.
Test with client [ITM-672 branch](https://github.com/NextCenturyCorporation/itm-evaluation-client/tree/ITM-672).
For testing instructions, see the [client PR](https://github.com/NextCenturyCorporation/itm-evaluation-client/pull/64).
Note line 219 of `itm_session.py`.  It's a temporary line for testing this PR so that you don't have to see a dump of complete session history.  Please remind me to remove it prior to merging.  :)

ITM-672:  Add solo (standalone) training mode

---

README.md
swagger_server/itm/data/dryrun/test/removed_characters.yaml
swagger_server/itm/data/phase1/test/downstream_injuries.yaml
swagger_server/itm/data/phase1/test/removed_characters.yaml
swagger_server/itm/data/phase1/test/supply_consumption.yaml
swagger_server/itm/itm_action_handler.py

Several changes were made to be more in sync with the simulator:
- Successful treatments for new injuries:
- stomach laceration: hemostatic gauze
- chest laceration: hemostatic gauze
- neck laceration: hemostatic gauze
- shoulder laceration: hemostatic gauze
- bicep laceration: tourniquet
- Hemostatic gauze consumption:
- use hemo gauze instead of tourniquet on untreated punctures consumes supply
- use hemo gauze instead of pressure bandage/tourniquet on untreated lacerations consumes supply
- use hemo gauze instead of pressure bandage on untreated abrasions consumes supply
- use hemo gauze instead of pressure bandage/airway on untreated leg/face shrapnel consumes supply
- ~~Decompression needles can be placed anywhere in any quantity, consuming supplies~~
- Using an airway (on right or …

ITM-638: More sync with Sim re: treatments/supplies

---

swagger_server/itm/data/domains/triage/test/supply_consumption.yaml
swagger_server/itm/domains/triage/triage_action_handler.py
swagger_server/itm/itm_action_handler.py
swagger_server/itm/itm_alignment_target_reader.py
swagger_server/itm/itm_history.py
swagger_server/itm/itm_scenario_reader.py

Although there’s a larger conversation on how these unsuccessful treatments consume supplies, for now, to match the sim, the ADM API should consume hemostatic gauze and pressure bandages when used by ADMs to treat open abdominal wounds.
To test, run:
- `python itm_minimal_runner.py --session test --scenario supply_consumption --name itm877`
Maybe add `print(state.supplies)` in `itm_minimal_runner.py` line 239 (of `development` branch) so you can check the client output and see that the hemostatic gauze and pressure bandage count went down after their respective attempted treatments.
NOTE:  I also removed the decompression needle treatment from the test, since the behavior it was testing was left on the cutting room floor of its PR but was inadvertently left in the test.
NOTE2:  I've been …

ITM-877:  Consume supplies upon unsuccessful open abdominal wound treatment

---

swagger/base_swagger.yaml
swagger/swagger.yaml
swagger_server/controllers/itm_ta2_eval_controller.py
swagger_server/itm/itm_session.py

See [ticket](https://nextcentury.atlassian.net/browse/ITM-497) and [client PR](https://github.com/NextCenturyCorporation/itm-evaluation-client/pull/71).
Exposed server-side action validation code via a simple endpoint.
To test, verify that normal operations still work (`test`, `adept`, `soartech` sessions).  You shouldn't need the TA1 servers, so you can launch the server with the `-t` option.  You also might try hacking the `itm_minimal_client.py` to make some invalid actions (both regular and intent actions) to see that the API catches invalid actions.
For example, near the beginning of the client's `get_net_action()` function, add:
```
if random_action.intent_action:
random_action.character_id = 'foobar'
```
or something like that.  Or change `get_random_supply()` to return `foobar` …

ITM-497:  Add action validation to API

---

README.md
swagger_server/__main__.py
swagger_server/controllers/itm_ta2_eval_controller.py
swagger_server/itm/itm_session.py

See [ticket](https://nextcentury.atlassian.net/browse/ITM-488).
- Support multiple simultaneous sessions with the same adm_name.
- Use the `session_id` as the “key” and don’t reuse sessions with the same `adm_name` like it used to.
- When the hard cap of active sessions is reached, clear out and re-use a completed session (one that has completed normally)
- If there are no completed sessions, then clear out and re-use a session that has timed out.
- Externalize session hard cap and session timeout via command-line parameters (with defaults).
To test, launch the server in test mode and set a low hard cap and session timeout, e.g.:
- `python -m swagger_server -t --timeout 1 --max_sessions 1`
Then in the `development` client, add a `sleep(20)` where it changes scenes (e.g., around line 245). …

ITM-488:  Improve simultaneous session handling

---

swagger_server/itm/itm_action_handler.py
swagger_server/itm/itm_history.py
swagger_server/itm/itm_scenario.py
swagger_server/itm/itm_scene.py
swagger_server/itm/itm_session.py
swagger_server/itm/ta1/itm_ta1_controller.py

The following changes were made:
- Log `action_id` and `justification` in “Take Action” and “Intend Action” history;
- Log `action_id` in “Respond to TA1 Probe” history;
- Log `start_time` and `domain` in “Start Scenario” history;
- Log `end_time` in “Scenario ended” history while renaming `elapsed_time` to `simulated_elapsed_time`;
- Replicate `start_time` and `end_time` in `metadata` (evaluation) block;
- Log `adm_profile` and `domain` in metadata;
- Log session start time in JSON and session end time and duration in server logging; and
- Better handle `NaN` session alignment score (see [this comment](https://github.com/NextCenturyCorporation/itm-evaluation-server/pull/122#issuecomment-2725325213) from an un-merged PR).
Unrelated, this also fixes the return code after validating an …

ITM-974: Expanded/improved history logging.

---

.gitignore
swagger_server/itm/data/domains/p2triage/config.ini.template
swagger_server/itm/domains/p2triage/csv_preprocessor.py
swagger_server/itm/domains/p2triage/p2triage_action_handler.py
swagger_server/itm/domains/p2triage/scenario_converter.py
swagger_server/itm/itm_session.py

This code is identical to the recently merged [ITM-1053](https://github.com/NextCenturyCorporation/itm-evaluation-server/pull/140).
For a sanity check, though, be sure you can exercise the 1d training scenarios:
- `python -m swagger_server`
- `python itm_minimal_runner --session adept --training full --name train1d`
[ITM-1053]: https://nextcentury.atlassian.net/browse/ITM-1053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Dev-to-main for July training update
